// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/age/age.proto

/*
Package tencent_user_age is a generated protocol buffer package.

It is generated from these files:
	src/proto/age/age.proto

It has these top-level messages:
	AddAgeRequest
	AddAgeResponse
*/
package tencent_user_age

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddAgeRequest struct {
	Age string `protobuf:"bytes,1,opt,name=age" json:"age,omitempty"`
}

func (m *AddAgeRequest) Reset()                    { *m = AddAgeRequest{} }
func (m *AddAgeRequest) String() string            { return proto.CompactTextString(m) }
func (*AddAgeRequest) ProtoMessage()               {}
func (*AddAgeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddAgeRequest) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

type AddAgeResponse struct {
	Age string `protobuf:"bytes,1,opt,name=age" json:"age,omitempty"`
}

func (m *AddAgeResponse) Reset()                    { *m = AddAgeResponse{} }
func (m *AddAgeResponse) String() string            { return proto.CompactTextString(m) }
func (*AddAgeResponse) ProtoMessage()               {}
func (*AddAgeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddAgeResponse) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func init() {
	proto.RegisterType((*AddAgeRequest)(nil), "tencent.user.age.AddAgeRequest")
	proto.RegisterType((*AddAgeResponse)(nil), "tencent.user.age.AddAgeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AgeService service

type AgeServiceClient interface {
	// Sends a greeting
	AddAge(ctx context.Context, in *AddAgeRequest, opts ...grpc.CallOption) (*AddAgeResponse, error)
}

type ageServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgeServiceClient(cc *grpc.ClientConn) AgeServiceClient {
	return &ageServiceClient{cc}
}

func (c *ageServiceClient) AddAge(ctx context.Context, in *AddAgeRequest, opts ...grpc.CallOption) (*AddAgeResponse, error) {
	out := new(AddAgeResponse)
	err := grpc.Invoke(ctx, "/tencent.user.age.AgeService/AddAge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgeService service

type AgeServiceServer interface {
	// Sends a greeting
	AddAge(context.Context, *AddAgeRequest) (*AddAgeResponse, error)
}

func RegisterAgeServiceServer(s *grpc.Server, srv AgeServiceServer) {
	s.RegisterService(&_AgeService_serviceDesc, srv)
}

func _AgeService_AddAge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgeServiceServer).AddAge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencent.user.age.AgeService/AddAge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgeServiceServer).AddAge(ctx, req.(*AddAgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tencent.user.age.AgeService",
	HandlerType: (*AgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAge",
			Handler:    _AgeService_AddAge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/age/age.proto",
}

func init() { proto.RegisterFile("src/proto/age/age.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x4c, 0x4f, 0x05, 0x61, 0x3d, 0x30, 0x4f, 0x48, 0xa0,
	0x24, 0x35, 0x2f, 0x39, 0x35, 0xaf, 0x44, 0xaf, 0xb4, 0x38, 0xb5, 0x48, 0x2f, 0x31, 0x3d, 0x55,
	0x49, 0x91, 0x8b, 0xd7, 0x31, 0x25, 0xc5, 0x31, 0x3d, 0x35, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8,
	0x44, 0x48, 0x80, 0x8b, 0x39, 0x31, 0x3d, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4,
	0x54, 0x52, 0xe2, 0xe2, 0x83, 0x29, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0x54, 0x63, 0x14,
	0xcd, 0xc5, 0xe5, 0x98, 0x9e, 0x1a, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xcb, 0xc5,
	0x06, 0xd1, 0x21, 0x24, 0xaf, 0x87, 0x6e, 0xa3, 0x1e, 0x8a, 0x75, 0x52, 0x0a, 0xb8, 0x15, 0x40,
	0x2c, 0x53, 0x62, 0x48, 0x62, 0x03, 0x3b, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x35, 0x0c,
	0x7f, 0xc4, 0xd7, 0x00, 0x00, 0x00,
}
