
# Client configuration
# [client]

# Monitor configuration
#
# monitor.params
#	Monitor's params to init
#	Gofra take the statsd as the default monitor system
#	so the params has 2 parts(all in a string array)
#		1.statsd's UDP address
#		2.the project's name
#	eg:
#		params=["127.0.0.1:8125", "demo"]
[monitor]
    params=["127.0.0.1:8125", "demo_benchmark"]

# Tracing configuration
#
# tracing.params
#       tracing's params to init
#       Gofra take the jaeger as the default tracing system
#       so the params has 2 parts(all in a string array)
#               1.jaeger's agent udp address
#               2.the project's name
#       eg:
#               params=["127.0.0.1:6831", "demo"]
[tracing]
    params=["127.0.0.1:6831", "demo_benchmark"]
